using System.Globalization;
using System.Xml.Linq;

namespace AtlasWH3.Formats.Battle;

/// <summary>Cell-space box, inclusive, image orientation (row 0 = north), as stored in battle_locations_map.</summary>
public readonly record struct CellBox(int MinX, int MinY, int MaxX, int MaxY)
{
    public bool Contains(int x, int y) => x >= MinX && x <= MaxX && y >= MinY && y <= MaxY;
    public int Area => (MaxX - MinX + 1) * (MaxY - MinY + 1);
    public CellBox Offset(int dx, int dy) => new(MinX + dx, MinY + dy, MaxX + dx, MaxY + dy);
}

/// <summary>A battle catchment area as BOB builds it from a BattleCatchmentArea entity and its Boundary child.</summary>
public sealed record BattleCatchment(
    string Id, IReadOnlyList<string> Types, string RedirectTo, string Culture,
    (int X, int Y) Centre, CellBox Box, string? BoundaryId)
{
    /// <summary>The catchment lists a Terry entity can put an area in (encampments are generated by BOB from tiles).</summary>
    public static readonly string[] EditableTypes = ["land_ambush", "settlement_standard", "settlement_unfortified", "gate_battle"];
}

/// <summary>
/// Reads and writes the catchment entities of a battle Terry layer (see docs/bob-battle-terrain-sources.md in BattleMaps).
/// BOB (bob_terrain FUN_180004840) takes: name = entity id; lists = <c>type</c> (comma separated); infield centre = the
/// entity's ECTransform position; aabb = the ECRectangle world bounds of its last Logical child; areas are added to
/// each list in entity order. World → cell: cx = trunc(x/256) + W/2, cy = ceil(H/2) − trunc(z/256).
/// </summary>
public static class BattleCatchmentLayer
{
    public static List<BattleCatchment> Read(string layerPath, int mapWidth, int mapHeight) =>
        Read(XDocument.Load(layerPath), mapWidth, mapHeight);

    public static List<BattleCatchment> Read(XDocument doc, int mapWidth, int mapHeight)
    {
        var root = doc.Root!;
        var ordered = root.Element("entities")?.Elements("entity").ToList() ?? [];
        var entities = ordered.ToDictionary(e => (string)e.Attribute("id")!, e => e);
        var children = LogicalChildren(root);

        var result = new List<BattleCatchment>();
        foreach (var e in ordered)
        {
            var area = e.Element("ECBattleCatchmentArea");
            if (area == null) continue;
            var id = (string)e.Attribute("id")!;
            var types = ((string?)area.Attribute("type") ?? (string?)area.Attribute("catchment_type") ?? "")
                .Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
            var (px, _, pz) = Position(e);
            var centre = ToCell(px, pz, mapWidth, mapHeight);

            var box = new CellBox(centre.X, centre.Y, centre.X, centre.Y);
            string? boundaryId = null;
            if (children.TryGetValue(id, out var kids) && kids.Count > 0 && entities.TryGetValue(kids[^1], out var boundary)
                && boundary.Element("ECRectangle") is { } rect)
            {
                boundaryId = kids[^1];
                var (bx, _, bz) = Position(boundary);
                var hw = Float(rect, "width") / 2;
                var hh = Float(rect, "height") / 2;
                var a = ToCell(bx - hw, bz - hh, mapWidth, mapHeight);
                var b = ToCell(bx + hw, bz + hh, mapWidth, mapHeight);
                box = new CellBox(Math.Min(a.X, b.X), Math.Min(a.Y, b.Y), Math.Max(a.X, b.X), Math.Max(a.Y, b.Y));
            }
            result.Add(new BattleCatchment(id, types, (string?)area.Attribute("redirect_to") ?? "",
                (string?)area.Attribute("culture") ?? "", centre, box, boundaryId));
        }
        return result;
    }

    /// <summary>
    /// Replaces the catchment entities (and their Boundary children and Logical links) in <paramref name="doc"/> with
    /// <paramref name="catchments"/>, in list order; every other entity and association is kept as it was. Catchments
    /// without a boundary id get a new unique one.
    /// </summary>
    public static void Write(XDocument doc, IReadOnlyList<BattleCatchment> catchments, int mapWidth, int mapHeight)
    {
        var root = doc.Root!;
        var entitiesEl = root.Element("entities") ?? new XElement("entities");
        if (entitiesEl.Parent == null) root.AddFirst(entitiesEl);
        var children = LogicalChildren(root);

        // Drop the old catchment entities and their boundaries.
        var old = entitiesEl.Elements("entity").Where(e => e.Element("ECBattleCatchmentArea") != null).ToList();
        var oldIds = old.Select(e => (string)e.Attribute("id")!).ToHashSet();
        var oldBoundaries = oldIds.SelectMany(id => children.GetValueOrDefault(id) ?? []).ToHashSet();
        foreach (var e in entitiesEl.Elements("entity").Where(e =>
                     oldIds.Contains((string)e.Attribute("id")!)
                     || oldBoundaries.Contains((string)e.Attribute("id")!) && e.Element("ECBattleCatchmentAreaBoundary") != null).ToList())
            e.Remove();

        var associations = root.Element("associations") ?? new XElement("associations");
        if (associations.Parent == null) root.Add(associations);
        var logical = associations.Element("Logical") ?? new XElement("Logical");
        if (logical.Parent == null) associations.Add(logical);
        foreach (var from in logical.Elements("from").Where(f => oldIds.Contains((string)f.Attribute("id")!)).ToList())
            from.Remove();

        var used = entitiesEl.Elements("entity").Select(e => (string)e.Attribute("id")!).ToHashSet(StringComparer.OrdinalIgnoreCase);
        foreach (var c in catchments) used.Add(c.Id);
        foreach (var c in catchments.Where(c => c.BoundaryId != null)) used.Add(c.BoundaryId!);
        var ids = new IdSource(used);

        var n = 0;
        foreach (var c in catchments)
        {
            var boundaryId = c.BoundaryId ?? ids.Next();
            var (px, pz) = CellToWorld(c.Centre.X, c.Centre.Y, mapWidth, mapHeight);
            var (x0, _) = CellToWorld(c.Box.MinX, 0, mapWidth, mapHeight);
            var (x1, _) = CellToWorld(c.Box.MaxX, 0, mapWidth, mapHeight);
            var (_, z1) = CellToWorld(0, c.Box.MinY, mapWidth, mapHeight);   // north edge = larger z
            var (_, z0) = CellToWorld(0, c.Box.MaxY, mapWidth, mapHeight);
            entitiesEl.Add(
                new XElement("entity", new XAttribute("id", c.Id), new XAttribute("name", $"BCA_{n++}"),
                    new XElement("ECBattleCatchmentArea",
                        new XAttribute("type", string.Join(",", c.Types)),
                        new XAttribute("redirect_to", c.RedirectTo),
                        new XAttribute("ambient_light_environments", ""),
                        new XAttribute("procedural", "false"),
                        new XAttribute("culture", c.Culture)),
                    new XElement("ECPlayerDeploymentLocations", new XAttribute("deployment_locations", "")),
                    Transform(px, pz),
                    new XElement("ECTransform2D"),
                    new XElement("ECRectangle", new XAttribute("width", "0"), new XAttribute("height", "0")),
                    new XElement("ECTileAlignment")),
                new XElement("entity", new XAttribute("id", boundaryId), new XAttribute("name", "Boundary"),
                    new XElement("ECBattleCatchmentAreaBoundary"),
                    Transform((x0 + x1) / 2, (z0 + z1) / 2),
                    new XElement("ECTransform2D"),
                    new XElement("ECRectangle", new XAttribute("width", Num(x1 - x0)), new XAttribute("height", Num(z1 - z0)))));
            logical.Add(new XElement("from", new XAttribute("id", c.Id), new XElement("to", new XAttribute("id", boundaryId))));
        }
    }

    /// <summary>A new layer document holding only catchments.</summary>
    public static XDocument NewLayer() =>
        new(new XDeclaration("1.0", "UTF-8", null),
            new XElement("layer", new XAttribute("version", "35"), new XElement("entities"),
                new XElement("associations", new XElement("Logical"))));

    public static void Save(XDocument doc, string path)
    {
        var temp = path + ".tmp";
        using (var writer = new StreamWriter(temp, false, new System.Text.UTF8Encoding(false)) { NewLine = "\n" })
            doc.Save(writer);
        File.Move(temp, path, overwrite: true);
    }

    /// <summary>bob_terrain FUN_18000d710.</summary>
    public static (int X, int Y) ToCell(double worldX, double worldZ, int mapWidth, int mapHeight) =>
        ((int)worldX / 256 + mapWidth / 2, (int)Math.Ceiling(mapHeight * 0.5) - (int)worldZ / 256);

    /// <summary>A world coordinate inside cell (cx, cy), picked so <see cref="ToCell"/> maps back to it.</summary>
    public static (double X, double Z) CellToWorld(int cx, int cy, int mapWidth, int mapHeight)
    {
        static double Axis(int k) => k == 0 ? 0 : k > 0 ? k * 256 + 128 : k * 256 - 128;
        return (Axis(cx - mapWidth / 2), Axis((int)Math.Ceiling(mapHeight * 0.5) - cy));
    }

    /// <summary>A fresh 15-hex-digit entity id not in <paramref name="used"/>.</summary>
    public sealed class IdSource(HashSet<string> used)
    {
        private long _n = DateTime.UtcNow.Ticks & 0xFFFFFFFFFFFFF;

        public string Next()
        {
            while (true)
            {
                var id = (0x1c00000000000000L + _n++).ToString("x15")[^15..];
                if (used.Add(id)) return id;
            }
        }
    }

    private static Dictionary<string, List<string>> LogicalChildren(XElement root)
    {
        var children = new Dictionary<string, List<string>>();
        foreach (var from in root.Element("associations")?.Element("Logical")?.Elements("from") ?? [])
            children[(string)from.Attribute("id")!] = from.Elements("to").Select(t => (string)t.Attribute("id")!).ToList();
        return children;
    }

    private static XElement Transform(double x, double z) =>
        new("ECTransform", new XAttribute("position", $"{Num(x)} 0 {Num(z)}"), new XAttribute("rotation", "0 0 0"),
            new XAttribute("scale", "1 1 1"), new XAttribute("pivot", "0 0 0"));

    private static string Num(double v) => v.ToString("0.###", CultureInfo.InvariantCulture);

    private static (double X, double Y, double Z) Position(XElement entity)
    {
        var p = ((string?)entity.Element("ECTransform")?.Attribute("position") ?? "0 0 0")
            .Split(' ', StringSplitOptions.RemoveEmptyEntries)
            .Select(s => double.Parse(s, CultureInfo.InvariantCulture)).ToArray();
        return (p.ElementAtOrDefault(0), p.ElementAtOrDefault(1), p.ElementAtOrDefault(2));
    }

    private static double Float(XElement e, string attribute) =>
        double.TryParse((string?)e.Attribute(attribute), NumberStyles.Float, CultureInfo.InvariantCulture, out var v) ? v : 0;
}
